# Generated by Django 5.1 on 2024-09-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='product_extension',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
