# Generated by Django 5.1 on 2024-09-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_software_product_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('manual_url', models.URLField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='manuals/')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
    ]
