# Generated by Django 5.1 on 2024-09-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_usermanual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanual',
            name='product_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
