# Generated by Django 5.1 on 2024-09-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_usermanual_product_name_alter_usermanual_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanual',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='usermanual',
            name='slug',
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
    ]
