# Generated by Django 5.1 on 2024-09-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_usermanual_pdf_file_remove_usermanual_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo1', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('logo2', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('logo1_x', models.IntegerField(default=50)),
                ('logo1_y', models.IntegerField(default=700)),
                ('logo2_x', models.IntegerField(default=50)),
                ('logo2_y', models.IntegerField(default=600)),
                ('qr_code_x', models.IntegerField(default=50)),
                ('qr_code_y', models.IntegerField(default=500)),
                ('instructions', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
